configversion: 3
#========================================
#             Custom Structures    
#========================================
#Wiki: https://github.com/ryandw11/CustomStructures/wiki
Schematics:

#A list containing all of the schematics.
#When you add a new schematic add it to this list.
    List:
        - demo
    #Change the name bellow with what you want. (Note: change the name in the list too!)
    demo:
        #The schematic file. Make sure to include the .schematic
        Schematic: 'demo.schematic'
        #What biome this a schematic can spawn in. Change to all for all.
        Biome: 'all'
        #The chance option
        Chance:
            #The number that can be picked out of 1000. So if 1 is picked than it spawns.
            Number: 1
            #The number that the ratio is out off.
            OutOf: 1000
        #If the structure can spawn in all worlds.
        AllWorlds: true
        #The y cord the structure will spawn on. Use -1 if you want it to be on the surface.
        SpawnY: -1
        #If you want air to be placed. True is air will be placed. False is air won't be placed.
        PlaceAir: true
        #If the above is false then the worlds it can spawn in:
        AllowedWorlds:
            - world