configversion: 3
#========================================
#             Custom Structures    
#========================================
#Wiki: https://github.com/ryandw11/CustomStructures/wiki

#Log extra information in console when generating structures
debug: false

#Allow Plugins to delete structures at will.
allowDeletion: true

Schematics:
    #Change the name bellow with what you want.
    demo:
        #The schematic file. Make sure to include the .schem
        Schematic: 'demo.schem'
        #What biome this a schematic can spawn in. Change to all for all.
        Biome: 'all'
        #The chance option
        Chance:
            #The number that can be picked out of 1000. So if 1 is picked than it spawns.
            Number: 1
            #The number that the ratio is out off.
            OutOf: 1000
        #If the structure can spawn in all worlds.
        AllWorlds: true
        #If the above is false then the worlds it can spawn in:
        AllowedWorlds:
            - world
        #The y cord the structure will spawn on. Use top if you want it to be on the surface.
        SpawnY: top
        #If you want air to be placed. True is air will be placed. False is air won't be placed.
        PlaceAir: true
        #If you want the structure to spawn in water or lava.
        spawnInLiquid: false
        #If the structure should be randomly rotated.
        randomRotation: false
        #Whitelisted blocks that the structure can spawn on. Remove this list if you do not want a whitelist.
        whitelistSpawnBlocks:
            - Grass_block
            - Dirt
            - Stone
            - air
        #List of lootTables for this Schematic, name and weight
        #Weight determines how often it will be chosen out of all the entries in the list.
        LootTables:
            lootTable: 5