name: CustomStructures
version: 1.3
main: com.ryandw11.structure.CustomStructures
author: Ryandw11
description: A plugin which allows you to spawn in custom structures!
depends: [WorldEdit]
commands:
    customstructure:
     description: Main command.
     aliases: [cs, cstructure, customs, cws]