configversion: 6
#========================================
#             Custom Structures    
#========================================
#Wiki: https://github.com/ryandw11/CustomStructures/wiki

#Log extra information in console when generating structures
debug: false

#bstats is where data is sent. https://bstats.org/plugin/bukkit/CustomStructures .
#Here is some more information on it like what it collects and how to disable it all together and not just for this plugin.
# https://bstats.org/getting-started
bstats: true

# Save where structures spawn into a yaml file.
# Enabling this option allows developers to use the API to get the location of structures.
logStructures: false

# If you want structures to spawn in the void, then enable this option.
# Keep this option of if you don't want any structures to spawn in the void
# for better performance.
spawnInVoid: false

Structures:
    - demo