package com.ryandw11.structure.loottables;

import org.bukkit.entity.Player;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.jetbrains.annotations.NotNull;

import java.util.Collection;

public interface LootTable {
    /**
     * Get the name of the loot table.
     *
     * @return the name of the loot table
     */
    @NotNull String name();

    /**
     * Returns a mutable list of loot generated by this LootTable.
     *
     * @param player player who triggers this loot table
     * @return a list of ItemStacks
     */
    @NotNull Collection<ItemStack> populateLoot(@NotNull Player player);

    /**
     * Attempt to fill an inventory with this LootTable's loot.
     *
     * @param inventory the inventory to fill
     * @param player    player triggering this loot table
     */
    void fillInventory(@NotNull Inventory inventory, @NotNull Player player);
}
